Name : Md Sadman Sayed Ratul <br>
Id   : 2215151007

**Use numpy to create a 3×3 matrix of random integers between 1 and 50.**

In [1]:
import numpy as np

random_matrix = np.random.randint(1, 51, (3, 3))

**Run the code twice**

In [3]:
print(random_matrix )

[[ 3 47 34]
 [11  4 47]
 [32 49  3]]


**With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.**

In [4]:
np.random.seed(10)
random_matrix = np.random.randint(1, 51, (3, 3))
print(random_matrix)

[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


**Without setting a seed, allowing random values to change each time.**

In [5]:
random_matrix = np.random.randint(1, 51, (3, 3))
print(random_matrix)

[[30 50  9]
 [10  1 43]
 [41 37 17]]


**Observe and explain the differences in outputs.**

- When using a fixed seed (np.random.seed(10)), NumPy ensures that the same random numbers are generated every time the code runs. This makes results reproducible, which is useful for debugging and sharing code.

- Without setting a seed, NumPy generates truly random numbers each time the script is run. As a result, the matrix values will change with every execution, making the outputs unpredictable.